networks:
  kafka-net:
    external: true

services:
  kafka:
    image: abhishekboppudi/kafka:latest
    container_name: Kafka_KRaft
    ports:
      - "9092:9092"   # internal PLAINTEXT listener
      - "9094:9094"   # external listener for host access
      - "9093:9093"   # controller listener (KRaft mode)
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@Kafka_KRaft:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://Kafka_KRaft:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CLUSTER_ID: "my-cluster-id"
    volumes:
      - ./kafka_data:/bitnami/kafka
    networks:
      - kafka-net
