process.roles=broker,controller
node.id=1
controller.quorum.voters=1@Kafka_KRaft:9093
listeners=PLAINTEXT://:9092,CONTROLLER://:9093
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
log.dirs=/bitnami/kafka/data