-- Hospital
create table if not exists hospital (
  hospital_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  address VARCHAR(300),
  city VARCHAR(100),
  state VARCHAR(100),
  zipcode VARCHAR(20),
  phone VARCHAR(30),
  email VARCHAR(150),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

-- Hospital administrator
create table if not exists hospital_administrator (
  admin_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100),
  gender VARCHAR(50),
  hospital_id BIGINT NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_admin_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
);

-- Hospital timings (session enum stored as ordinal int)
create table if not exists hospital_timings (
  timing_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL,
  session INT NOT NULL,                        -- enum ordinal
  slot_interval INT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  CONSTRAINT fk_timings_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
);

-- Doctor assignment
create table if not exists doctor_assignment (
  doctor_id bigint not null,
  hospital_id bigint not null,
  timing_id bigint not null,
  active boolean not null default true,
  created_at timestamp,
  updated_at timestamp,
  primary key (doctor_id, hospital_id, timing_id),
  constraint fk_assign_hospital foreign key (hospital_id) references hospital(hospital_id),
  constraint fk_assign_timing foreign key (timing_id) references hospital_timings(timing_id)
);

-- Appointment slot (slotType enum stored as ordinal int)
create table if not exists appointment_slot (
  hospital_id bigint not null,
  doctor_id bigint not null,
  appointment_date date not null,
  start_time time not null,
  patient_id bigint not null,
  timing_id bigint not null,
  reserved boolean not null default false,
  slot_type int,                               -- enum ordinal
  primary key (hospital_id, doctor_id, appointment_date, start_time, patient_id),
  constraint fk_slot_hospital foreign key (hospital_id) references hospital(hospital_id),
  constraint fk_slot_timing foreign key (timing_id) references hospital_timings(timing_id)
);

-- Diagnostics lab (LabTestType enum stored as ordinal int)
create table if not exists diagnostics_lab (
  lab_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  technician_name VARCHAR(150),
  phone VARCHAR(30),
  hospital_id BIGINT NOT NULL,
  type INT NOT NULL,                           -- enum ordinal
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT fk_lab_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
);

-- Lab report
create table if not exists lab_report (
  lab_report_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lab_id BIGINT NOT NULL,
  hospital_id BIGINT NOT NULL,
  patient_id BIGINT NOT NULL,
  report_file BYTEA NOT NULL,
  mime_type VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_report_lab FOREIGN KEY (lab_id) REFERENCES diagnostics_lab(lab_id),
  CONSTRAINT fk_report_hospital FOREIGN KEY (hospital_id) REFERENCES hospital(hospital_id)
);

create table if not exists doctor_invitation (
    invitation_id      bigserial primary key,
    hospital_id        bigint not null,
    doctor_id          bigint not null,
    status             varchar(20) not null default 'PENDING',
    created_at         timestamp not null default current_timestamp,
    responded_at       timestamp null,

    -- optional: track who created the invitation
    created_by         bigint null,

    expiryDate         timestamp not null,

    -- constraints
    constraint chk_status check (status in ('PENDING', 'ACCEPTED', 'REJECTED'))
);

-- Indexes for fast lookups
create index if not exists idx_invitation_hospital on doctor_invitation (hospital_id);
create index if not exists idx_invitation_doctor on doctor_invitation (doctor_id);
create index if not exists idx_invitation_status on doctor_invitation (status);


-- Billing (BillingStatus enum stored as ordinal int)
create table if not exists billing (
  billing_id bigint primary key,
  appointment_id bigint not null,
  hospital_id bigint not null,
  patient_id bigint not null,
  bill_amount numeric(12,2) not null,
  currency varchar(10) not null default 'INR',
  billing_status int not null,                 -- enum ordinal
  updated_at timestamp,
  constraint fk_billing_hospital foreign key (hospital_id) references hospital(hospital_id),
  constraint uq_billing_appointment unique (appointment_id)
);
