package com.pm.hospitalservice.entity;

import com.pm.common.constant.BillingStatus;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Setter
@Getter
@Entity
public class Billing {

  //billingid  is generated by billing-service
  @Id
  private long billingId;

  //AppointmentId is generated by appointment-service
  @Id
  private long appointmentId;

  private long hospitalId;

  private double billAmount;

  private String currency = "INR";

  private BillingStatus billingStatus;

  private LocalDateTime updatedAt;
}
